#!/bin/sh
set -e

make() {
    /usr/bin/make disport

    cat _disport/Makefile \
	| sed "s:^PORTNAME=.*:PORTNAME= $(disport_short_name)$(disport_pkg_suffix):" \
	| sed "s:^PORTVERSION=.*:PORTVERSION= $(disport_base_version)$(disport_patch_level):" \
	| sed "s:^GH_TAGNAME=.*:GH_TAGNAME= ${CIRRUS_CHANGE_IN_REPO}:" \
	| sed '
/CATEGORIES/ a\
CONFLICTS_INSTALL=
' \
	| sed "s:^CONFLICTS_INSTALL=.*:CONFLICTS_INSTALL= $(disport_short_name)*:" \
		  > _disport/Makefile

    tar -czf _disport.txz _disport
    curl -s -X POST --data-binary @_disport.txz http://${CIRRUS_HTTP_CACHE_HOST}/_disport-${CIRRUS_BUILD_ID}.txz
}

pkg() {
    /usr/sbin/pkg install -y tailscale
    service tailscaled enable
    service tailscaled start
    tailscale up --authkey ${TS_KEY} --hostname cirrus-${CIRRUS_REPO_NAME}-${CIRRUS_BRANCH}-${CIRRUS_BUILD_ID}
    mkdir -m 700 /.cirrus_ssh
    echo "${PKG_HOST}" > /.cirrus_ssh/known_hosts
    echo "${SSH_KEY}" > /.cirrus_ssh/key
    chmod 600 /.cirrus_ssh/*
    fetch -o _disport.txz http://${CIRRUS_HTTP_CACHE_HOST}/_disport-${CIRRUS_BUILD_ID}.txz
    tar -xzf _disport.txz
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "rm -rf ports/$(disport_full_name) && mkdir -p ports/$(disport_full_name)"
    scp -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts _disport/* cirrus@pkg:ports/$(disport_full_name)
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "sudo poudriere bulk -j 131RC6 -p default -O cirrus $(disport_full_name)"
}

disport_patch_level() {
    if [ $(disport_is_release) = "no" ]
    then
	date -u "+p%Y%m%d%H%M%S"
    fi
}

disport_pkg_suffix() {
    if [ $(disport_is_release) = "no" ]
    then
	echo "-${CIRRUS_BRANCH}"
    fi    
}

disport_base_version() {
    grep PORTVERSION disport/Makefile | sed 's:PORTVERSION= ::'
}

disport_is_release() {
    if [ "v$(disport_base_version)" = "$CIRRUS_TAG" ]
    then
	echo "yes"
    else
	echo "no"
    fi
}

disport_short_name() {
    echo $DISPORT_NAME | sed 's:.*\/::'
}

disport_full_name() {
    echo "${DISPORT_NAME}$(disport_pkg_suffix)"
}

"$@"
