#!/bin/sh
set -e

make() {
    /usr/bin/make disport

    echo "PORTVERSION=$(disport_base_version)$(disport_patch_level)" >> _disport/options
    echo "PKGNAMESUFFIX=$(disport_pkg_suffix)" >> _disport/options
    echo "GH_TAGNAME=$CIRRUS_CHANGE_IN_REPO" >> _disport/options
    echo "CONFLICTS_INSTALL=${PORTNAME}*"

    tar -czf _disport.txz _disport
    curl -s -X POST --data-binary @_disport.txz http://${CIRRUS_HTTP_CACHE_HOST}/_disport-${CIRRUS_BUILD_ID}.txz
}

pkg() {
    /usr/sbin/pkg install -y tailscale
    service tailscaled enable
    service tailscaled start
    tailscale up --authkey ${TS_KEY} --hostname cirrus-${CIRRUS_REPO_NAME}-${CIRRUS_BRANCH}-${CIRRUS_BUILD_ID}
    mkdir -m 700 /.cirrus_ssh
    echo "${PKG_HOST}" > /.cirrus_ssh/known_hosts
    echo "${SSH_KEY}" > /.cirrus_ssh/key
    chmod 600 /.cirrus_ssh/*
    fetch -o _disport.txz http://${CIRRUS_HTTP_CACHE_HOST}/_disport-${CIRRUS_BUILD_ID}.txz
    tar -xzf _disport.txz
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "mkdir -p ports/${DISPORT_NAME}"
    scp -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts _disport/* cirrus@pkg:ports/${DISPORT_NAME}
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "sudo mkdir -p /usr/local/etc/poudriere.d/options/$(disport_flat_dir)"
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "sudo cp /home/cirrus/ports/${DISPORT_NAME}/options /usr/local/etc/poudriere.d/options/$(disport_flat_dir)/"
    ssh -i /.cirrus_ssh/key -o UserKnownHostsFile=/.cirrus_ssh/known_hosts cirrus@pkg "sudo poudriere bulk -j 131RC6 -p default -O cirrus ${DISPORT_NAME}"
}

disport_patch_level() {
    if [ $(disport_is_release) = "no" ]
    then
	date -u "+p%Y%m%d%H%M%S"
    fi
}

disport_pkg_suffix() {
    if [ $(disport_is_release) = "no" ]
    then
	echo "-${CIRRUS_BRANCH}"
    fi    
}

disport_base_version() {
    grep PORTVERSION disport/Makefile | sed 's:PORTVERSION= ::'
}

disport_is_release() {
    if [ "v$(disport_base_version)" = "$CIRRUS_TAG" ]
    then
	echo "yes"
    else
	echo "no"
    fi
}

disport_flat_dir() {
    echo $DISPORT_NAME | sed 's:/:_:'
}

"$@"
